import { Config } from '../types';

/**
 * Get LLM provider information for review metadata
 */
export function getLLMInfo(config: Config): string {
  let providerInfo = '';

  if (config.llmProvider === 'anthropic') {
    providerInfo = 'Anthropic Claude (claude-sonnet-4-20250514)';
  } else if (config.llmProvider === 'ollama') {
    const model = config.ollamaModel || 'unknown';
    providerInfo = `Ollama (${model})`;
  } else {
    providerInfo = config.llmProvider;
  }

  return providerInfo;
}

/**
 * Get a formatted string with LLM provider and timestamp
 */
export function getReviewMetadata(config: Config): string {
  const llmInfo = getLLMInfo(config);
  const timestamp = new Date().toISOString();

  return `Review generated by ${llmInfo} at ${timestamp}`;
}
